backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "General Settings"
        file: "public/settings.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Logo URL", name: "logoUrl", widget: "string"}

  - name: "categories"
    label: "Categories"
    folder: "public/data/categories"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Image URL", name: "imageUrl", widget: "string"}
